ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "loyaltyTier1Visits" INTEGER NOT NULL DEFAULT 4;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "loyaltyTier1Percent" INTEGER NOT NULL DEFAULT 50;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "loyaltyTier2Visits" INTEGER NOT NULL DEFAULT 8;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "loyaltyTier2Percent" INTEGER NOT NULL DEFAULT 100;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "loyaltyMaxDays" INTEGER NOT NULL DEFAULT 25;
ALTER TABLE "Customer" ADD COLUMN IF NOT EXISTS "loyaltyLastVisit" TIMESTAMP(3);
