-- Modelo fiscal (IVA) + tipo de factura. Todo aditivo con defaults (no toca datos existentes).
DO $$ BEGIN
  CREATE TYPE "InvoiceType" AS ENUM ('NORMAL', 'ELECTRONICA');
EXCEPTION WHEN duplicate_object THEN null; END $$;

ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "responsableIVA" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Company" ADD COLUMN IF NOT EXISTS "preciosIncluyenIVA" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "Inventory" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "Service" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0;

ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "invoiceType" "InvoiceType" NOT NULL DEFAULT 'NORMAL';
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "subtotal" DECIMAL(14,2);
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "taxTotal" DECIMAL(14,2) NOT NULL DEFAULT 0;

ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "taxRate" DECIMAL(5,2) NOT NULL DEFAULT 0;
ALTER TABLE "SaleItem" ADD COLUMN IF NOT EXISTS "taxAmount" DECIMAL(14,2) NOT NULL DEFAULT 0;
