-- Nuevas verticales de negocio
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'ODONTOLOGIA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'SUPERMERCADO';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'DROGUERIA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'ROPA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'FRUVER';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'FLORISTERIA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'COMIDA_RAPIDA';
ALTER TYPE "BusinessType" ADD VALUE IF NOT EXISTS 'CAFETERIA';
